#!/bin/bash

echo '====================='
echo 'CHOOSE PROJECT TYPE:'
echo '[1] Basic'
echo '[2] JQuery'
echo '[3] Vue'
echo '[4] Node'
echo '[5] Web-Scraper'
echo
echo '[x] exit script'
echo '====================='
read choice

if [ $choice = '1' ] || [ $choice = '2' ] || [ $choice = '3' ] || [ $choice = '4' ] || [ $choice = '5' ]
	then
	echo	
	echo 'ENTER A PROJECT NAME:'
	read name
	echo
fi

case $choice in 
	
	1) 
		cp -rfiv ~/Documents/TEMPLATES/BASIC ~/Documents/Projects/$name
		echo "BASIC template copied, renamed "$name" and sent to Projects"
		;;	
	2) 
		cp -rfiv ~/Documents/TEMPLATES/JQ_BS_EXPRESS ~/Documents/Projects/$name
		echo "JQUERY template copied, renamed "$name" and sent to Projects"
		;;
	3)
		cp -rfiv ~/Documents/TEMPLATES/VUE_BASIC ~/Documents/Projects/$name
	 	echo "VUE template copied, renamed "$name" and sent to Projects"
	 	;;
	4)
		cp -rfiv ~/Documents/TEMPLATES/NODE_APP ~/Documents/Projects/$name
	 	echo "NODE template copied, renamed "$name" and sent to Projects"
	 	;;
	5)
		cp -rfiv ~/Documents/TEMPLATES/WEB-SCRAPER ~/Documents/Projects/$name
	 	echo "WEB-SCRAPER template copied, renamed "$name" and sent to Projects"
	 	;;
	x) 
		exit
		;;
	*) 
		echo
		echo "INVALID CHOICE"
		$(basename $0) && exit
		;;
esac	





