#!/bin/bash

## Securely transfer files up to a server

echo '==========================='
echo 'ENTER SERVER ADDRESS:'
read address
echo
echo '==========================='
echo 'ENTER FOLDER NAME:'
read folder
echo
echo '==========================='
echo 'ENTER FILE TO COPY:'
read copy
echo

if [[ ! -z $address ]] && [[ ! -z $folder ]] && [[ ! -z $copy ]]
	then
	scp ~/Documents/Projects/$folder/$copy root@$address:/opt/$folder/$copy
else
	echo 'Missing arguments. Try again.'
	echo
	$(basename $0) && exit
fi