#!/bin/bash

##SENDS '.bash_aliases' TO SERVER AT $1

echo 'send .bash_aliases?[y/n]'
read ba 
if [ $ba = 'y' ]
	then
	scp ~/.bash_aliases root@$1:.bash_aliases
	echo ".bash_aliases uploaded to remote server"
fi

echo 'send setup script?[y/n]'
read script
if [ $script = 'y' ]
	then
	scp ~/Documents/SCRIPTS/setupServer root@$1:setup
	echo 'setup script uploaded to remote server'
fi