#!/bin/bash

##SENDS '.bash_aliases' AND 'Setup Script' TO SERVER AT $1

echo '=========================='
echo 'send .bash_aliases?[y/n]'
read ba 
if [ $ba = 'y' ]
	then
	scp ~/.bash_aliases root@$1:.bash_aliases
	echo ".bash_aliases UPLOADED TO REMOTE SERVER @ "$1""
fi

echo '=========================='
echo 'send setup script?[y/n]'
read script
if [ $script = 'y' ]
	then
	scp ~/Documents/SCRIPTS/setupServer root@$1:Setup
	echo "setup script UPLOADED TO REMOTE SERVER @ "$1""
fi