#!/bin/bash

## Automates NODE, NPM, FOREVER, MONGO installation on a server

apt-get update && 
echo 'UPDATED'
apt install npm && 
echo 'INSTALLED NPM'
apt install nodejs-legacy &&
echo 'INSTALLED NODE'
npm install -g forever &&
echo 'INSTALLED FOREVER'

echo '======================='
echo 'install MondoDB?[y/n]'
read mongo
if [ $mongo = 'y' ]
	then
	apt install mongodb-server &&
	echo 'installed mongo'
fi

echo
echo 'ALL PACKAGES INSTALLED SUCCESSFULLY'
echo

echo '======================='
echo 'delete script?[y/n]'
read confirm
if [ $confirm = 'y' ]
	then
	rm $0 
	echo 'SCRIPT DELETED'
	exit
fi




