#!/bin/bash

## Automates NODE, NPM, FOREVER, MONGO, Web-Scraper installation on a server

apt-get update && 
echo 'UPDATED'
apt install npm && 
echo 'INSTALLED NPM'
apt install nodejs-legacy &&
echo 'INSTALLED NODE'
npm install -g forever &&
echo 'INSTALLED FOREVER'

echo '======================='
echo 'install MongoDB?[y/n]'
read mongo
if [ $mongo = 'y' ]
	then
	apt install mongodb-server &&
	echo 'INSTALLED MONGO'
fi

echo '=========================='
echo 'install Web-Scraper?[y/n]'
read scraper
if [ $scraper = 'y' ]
	then
	sudo apt-get update &&
	echo 'UPDATED'
	npm install -g electron-prebuilt &&
	echo 'INSTALLED ELECTRON'
	sudo apt-get install build-essential clang libdbus-1-dev libgtk2.0-dev libnotify-dev libgnome-keyring-dev libgconf2-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-multilib g++-multilib curl gperf bison &&
	echo 'INSTALLED DEPENDENCIES'
	apt-get install xvfb &&
	echo 'INSTALLED XVFB'
fi

echo
echo 'ALL PACKAGES INSTALLED SUCCESSFULLY'
echo

echo '======================='
echo 'delete script?[y/n]'
read delete
if [ $delete = 'y' ]
	then
	rm $0 
	echo 'SCRIPT DELETED'
	exit
fi




